---
- name: Playbook para hacer el deploy de la aplicación web Moodle
  hosts: frontend
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Descargar el código fuente de Moodle
      get_url:
        url: https://github.com/moodle/moodle/archive/refs/tags/v4.3.1.zip
        dest: /tmp/
        mode: 0755

    - name: Instalar unzip
      apt: 
        name: unzip
        state: present

    - name: Descomprimir el paquete de Moodle
      unarchive:
        src: /tmp/moodle-4.3.1.zip
        dest: /tmp/
        remote_src: true
        
    - name: Descomprimir el código fuente de Moodle
      copy:
        src: /tmp/moodle-4.3.1/
        dest: /var/www/html/
        remote_src: yes

    - name: Modificamos los permisos del directorio /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
        mode: 0755
        
    - name: Instalar Moodle desde PHP CLI
      command:
        php install.php \
        --lang={{ moodle.lang }} \
        --wwwroot="{{ moodle.wwwroot  }}" \
        --dataroot={{ moodle.dataroot  }} \
        --dbtype={{ moodle.dbtype }} \
        --dbhost={{ moodle.dbhost }} \
        --dbname={{ moodle.dbname }} \
        --dbuser={{ moodle.dbuser }} \
        --dbpass={{ moodle.dbpass }} \
        --fullname="{{ moodle.fullname }}" \
        --shortname="{{ moodle.shortname }}" \
        --summary="{{ moodle.summary }}" \
        --adminuser={{ moodle.adminuser }} \
        --adminpass={{ moodle.adminpass }} \
        --adminemail={{ moodle.adminemail }} \
        --non-interactive \
        --agree-license
      args:
        chdir: /var/www/html/admin/cli/
      
    - name: Eliminar el directorio de instalación
      file:
        path: /var/www/html/admin/cli/
        state: absent

    - name: Modificamos el valor max_input_vars de PHP
      replace: 
        path: /etc/php/8.3/apache2/php.ini
        regexp: ;max_input_vars = 1000
        replace: max_input_vars = 5000

    - name: Cambiar el propietario y el grupo del directorio /var/www/html
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Añadir configuración a config.php
      lineinfile:
        path: /var/www/html/config.php
        insertafter: '/$CFG->admin/'
        line: |
          $CFG->reverseproxy=1;
          $CFG->sslproxy=1;
